language: ruby
cache: bundler
before_install: gem update bundler
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - ruby-head
gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.2.10
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.4.9
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
notifications:
  email: false
