language: ruby
sudo: false
cache: bundler
before_install: gem update bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_edge.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.2.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.2.9
      gemfile: gemfiles/rails_edge.gemfile
    - rvm: 2.3.6
      gemfile: gemfiles/rails_edge.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_edge.gemfile
notifications:
  email: false
